// Mocks generated by Mockito 5.4.6 from annotations
// in nivara/test/features/music/interfaces_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nivara/features/music/domain/mood_category.dart' as _i7;
import 'package:nivara/features/music/domain/music_playlist.dart' as _i2;
import 'package:nivara/features/music/domain/music_repository.dart' as _i6;
import 'package:nivara/features/music/domain/music_service.dart' as _i3;
import 'package:nivara/features/music/domain/music_track.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMusicPlaylist_0 extends _i1.SmartFake implements _i2.MusicPlaylist {
  _FakeMusicPlaylist_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MusicService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicService extends _i1.Mock implements _i3.MusicService {
  MockMusicService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> play(_i5.MusicTrack? track) => (super.noSuchMethod(
        Invocation.method(
          #play,
          [track],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> skip() => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekTo(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [position],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [MusicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicRepository extends _i1.Mock implements _i6.MusicRepository {
  MockMusicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MusicPlaylist> getPlaylistForMood(_i7.MoodCategory? mood) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaylistForMood,
          [mood],
        ),
        returnValue: _i4.Future<_i2.MusicPlaylist>.value(_FakeMusicPlaylist_0(
          this,
          Invocation.method(
            #getPlaylistForMood,
            [mood],
          ),
        )),
      ) as _i4.Future<_i2.MusicPlaylist>);

  @override
  _i4.Future<List<_i5.MusicTrack>> getAllTracks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTracks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.MusicTrack>>.value(<_i5.MusicTrack>[]),
      ) as _i4.Future<List<_i5.MusicTrack>>);
}
